<?php
// $Id$
/**
 * @file wl_payment_processing.module
 * Provides simple checkout-style buttons or redirects for fixed price products or services.
 * NOTE: AUTH.NET's Simple Checkout dows not provide thank-you page redirects or payment capture reporting functionality 
 */
 
 /**
 * wl_payment_processing_menu function.
 *
 * Implementation of hook_menu.
 */
function wl_payment_processing_menu(){

	// create a page to present pay now button with address /paypal-form
	$items['paypal-form'] = array(
		'title' => 'Registration Payment Required',
		'page callback' => 'wl_paypal_form_page',
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);
	
	// create a page with address /paypal-thanks (button code should redirect here)	
	$items['paypal-thanks'] = array(
		'title' => 'Thanks For Your Payment',
		'page callback' => 'wl_paypal_complete_page',
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);
	
	// create a page that with address /paypal-capture-payment can be called by paypal to notify us of payment completions (button code should include this link)
	$items['paypal-capture-payment'] = array(
		'title' => 'PayPal Capture',
		'page callback' => 'wl_paypal_capture_payment_page',
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);
	
	// ** CUSTOM PAGES **
	
	// create a page to present pay now button
	$items['fire-and-ice'] = array(
		'title' => 'Fire and Ice Registration',
		'page callback' => 'wl_fire_and_ice_page',
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);
	
	// create a page to present pay now button
	$items['rafting'] = array(
		'title' => 'Rafting Registration',
		'page callback' => 'wl_rafting_page',
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);
	
	return $items;
}



/**
 * Menu callback page(s)
 */
function wl_paypal_form_page(){

	// Examples:
	
	// EITHER REDIRECT TO PAYPAL:
	// drupal_goto('https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=[BUTTON-ID HERE]&notify_url='.urlencode('http://'.$_SERVER['HTTP_HOST'].'/paypal-capture-payment'));

	// OR DISPLAY BUTTON CODE:
	// $output = '';
	// $output.= '[BUTTON CODE GOES HERE]';
	// return $output;

	$output = '';
	return $output;
}

function wl_fire_and_ice_page(){

	error_log('fire_and_ice');

	$output = '';
	$output.= '<form name="PrePage" method = "post" action = "https://Simplecheckout.authorize.net/payment/CatalogPayment.aspx">  <input type = "hidden" name = "LinkId" value ="f41e4bab-73cb-4c72-b8fc-c4173fb48f38" />  <input type = "image" src ="//content.authorize.net/images/buy-now-gold.gif" /> </form>';	
	return $output;
}


function wl_rafting_page(){

	error_log('rafting');

	$output = '';
	$output.= '<form name="PrePage" method = "post" action = "https://Simplecheckout.authorize.net/payment/CatalogPayment.aspx">  <input type = "hidden" name = "LinkId" value ="b04fae28-c36a-476b-aa72-3300c472dad9" />  <input type = "image" src ="//content.authorize.net/images/buy-now-gold.gif" /> </form>';
	return $output;
}



function wl_paypal_complete_page(){

	// define content for thanks page here

	$output = "Thanks very much for completing your registration.";
	return $output;

}

function wl_paypal_capture_payment_page(){

	$info = "";

	$myKeys = array_keys($_GET);
	$info.="GET Data:\r\n";
	for($i=0;$i<count($myKeys);$i++){
		$info.= $myKeys[$i].": ".$_GET[$myKeys[$i]]."\r\n";
	}
	$myKeys = array_keys($_POST);
	$info.="\r\n---------\r\n";
	$info.="POST Data:\r\n";
	for($i=0;$i<count($myKeys);$i++){
		$info.= $myKeys[$i].": ".$_POST[$myKeys[$i]]."\r\n";
	}
	
	$email_message = "PayPal payment captured:\n\n".$info;
	$subject = 'PayPal Registration Fee Captured';
	
	// choose who to send emails to / from here
	$message = array(
	  'id' => 'wl_paypal_fee_captured',
	  'to' => 'info@wanderlustfestival.com, support@malkine.com', //
	  'subject' => $subject,
	  'body' => $email_message,
	  'headers' => array('From' => 'info@wanderlustfestival.com'),
	);
	drupal_mail_send($message);
	
	$output = "Capture successful.";
	return $output;

}

