<?php
// $Id$
/**
 * @file wl_volunteer.module
 * Correlates login with SourceSpring ticketing and scheduling service.
 * Important: Admin users are configured with disabled SourceSpring services by default.
 */

 
 /**
 * wander_fb_menu function.
 *
 * Implementation of hook_menu.
 */
function wl_volunteer_menu(){
	$items['volunteer-form'] = array(
		'title' => 'Volunteer Application 2010',
		'page callback' => 'wl_volunteer_page',
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);
	$items['volunteer-form-complete'] = array(
		'title' => 'Volunteer Registration Complete',
		'page callback' => 'wl_volunteer_complete_page',
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);
	$items['volunteer-form-capture-payment'] = array(
		'title' => 'PayPal Capture',
		'page callback' => 'wl_volunteer_capture_payment_page',
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);
	/*
	$items['admin/settings/unified_login'] = array(
		'title' => 'Unified Login settings',
		'description' => 'Manage Unified Login settings.',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('unified_login_admin_settings'),
		'access arguments' => array('administer site configuration'),
		'type' => MENU_NORMAL_ITEM,
		'file' => 'unified_login.admin.inc',
	);
	*/
	return $items;
}


function wl_volunteer_complete_page(){

	$output = "Thanks very much for applying to become a volunteer at Wanderlust 2010.  We'll review your application shortly and will be in touch if we have any additional questions.  Final decisions will be announced on a rolling basis via email starting June 1, 2010.  If you have any questions, please email us at <a href='mailto:volunteer@wanderlustfestival.com'>volunteer@wanderlustfestival.com</a>.<br />&nbsp;<br />Hope to see you on the cable car.<br />&nbsp;<br />- Kat Murray, Volunteer Coordinator";
	return $output;

}

function wl_volunteer_capture_payment_page(){

	// mail payment info

	$info = "";

	$myKeys = array_keys($_GET);
	$info.="GET Data:\r\n";
	for($i=0;$i<count($myKeys);$i++){
		$info.= $myKeys[$i].": ".$_GET[$myKeys[$i]]."\r\n";
	}
	$myKeys = array_keys($_POST);
	$info.="\r\n---------\r\n";
	$info.="POST Data:\r\n";
	for($i=0;$i<count($myKeys);$i++){
		$info.= $myKeys[$i].": ".$_POST[$myKeys[$i]]."\r\n";
	}
	
	$email_message = "PayPal payment captured:\n\n".$info;
	$subject = 'PayPal Volunteer Registration Fee Captured';
	
	//error_log($email_message);
	$message = array(
	  'id' => 'wl_volunteer_fee_captured',
	  'to' => 'volunteer@wanderlustfestival.com', //, support@malkine.com
	  'subject' => $subject,
	  'body' => $email_message,
	  'headers' => array('From' => 'volunteer@wanderlustfestival.com'),
	);
	drupal_mail_send($message);
	
	$output = "Capture successful.";
	return $output;

}


/**
 * Menu callback page
 */
function wl_volunteer_page(){

	if ($_SERVER['SERVER_PORT']!=443 && stripos($_SERVER['HTTP_HOST'],'www.wanderlustfestival.com')!==FALSE){
		//error_log($_SERVER['HTTP_HOST']);
		drupal_goto("https://".$_SERVER['HTTP_HOST']."/volunteer-form"); // redirect to secure form
		exit();
	}

	$output = '';	

	//$output.= t("<div class=\"heading4\">The Application</div>\n");
	
	$output.= drupal_get_form('wl_volunteer_volform');
	
	return $output;

}

/**
 * Define the form
 * 
 */
function wl_volunteer_volform(){

	$form = NULL;
	
	// ============================ BASIC INFO

	$form['first_name'] = array(
		'#prefix' => "<div class=\"heading1\">Basic Info</div>",
		'#title' => t('First Name'),
		'#type' => 'textfield',
		'#default_value' => '',
		'#required' => TRUE,
	);
	$form['last_name'] = array(
		'#title' => t('Last Name'),
		'#type' => 'textfield',
		'#default_value' => '',
		'#required' => TRUE,
	);
	$form['cell_phone'] = array(
		'#title' => t('Cell Phone'),
		'#type' => 'textfield',
		'#default_value' => '',
		'#required' => TRUE,
	);
	$form['work_phone'] = array(
		'#title' => t('Work Phone'),
		'#type' => 'textfield',
		'#default_value' => '',
		'#required' => FALSE,
	);
	$form['street_address'] = array(
		'#title' => t('Street Address'),
		'#type' => 'textfield',
		'#default_value' => '',
		'#required' => TRUE,
	);
	$form['city'] = array(
		'#title' => t('City'),
		'#type' => 'textfield',
		'#default_value' => '',
		'#required' => TRUE,
	);
	$form['state'] = array(
		'#title' => t('State'),
		'#type' => 'textfield',
		'#default_value' => '',
		'#required' => TRUE,
	);
	$form['zip'] = array(
		'#title' => t('Zip'),
		'#type' => 'textfield',
		'#default_value' => '',
		'#required' => TRUE,
	);
	$form['email'] = array(
		'#title' => t('Email'),
		'#type' => 'textfield',
		'#default_value' => '',
		'#required' => TRUE,
	);
	$form['email_subscribe'] = array(
		'#type' => 'checkboxes',
		'#options' => array( 'opt_in' => t('Sign up for event information and updates') ),
		'#default_value' => array( 'opt_in' => 'opt_in' ),
	);
	
	$form['twitter'] = array(
		'#title' => t('Twitter'),
		'#type' => 'textfield',
		'#default_value' => '',
		'#required' => FALSE,
	);
	$form['im'] = array(
		'#title' => t('IM'),
		'#type' => 'textfield',
		'#default_value' => '',
		'#required' => FALSE,
	);
	$form['im_service'] = array(
		'#title' => t('IM Service'),
		'#type' => 'textfield',
		'#default_value' => '',
		'#required' => FALSE,
	);
	$form['facebook'] = array(
		'#title' => t('Facebook'),
		'#type' => 'textfield',
		'#default_value' => '',
		'#required' => FALSE,
	);
	$form['myspace'] = array(
		'#title' => t('Myspace'),
		'#type' => 'textfield',
		'#default_value' => '',
		'#required' => FALSE,
	);

	// ============================ ABOUT YOU
	
	$form['age'] = array(
		'#prefix' => "<div class=\"heading1\">About You</div>",
		'#title' => t('Age'),
		'#type' => 'textfield',
		'#default_value' => '',
		'#required' => FALSE,
	);
	$form['yoga'] = array(
		'#title' => t('Do you practice yoga?'),
		'#type' => 'radios',
		'#options' => array( 'Yes' => 'Yes', 'No' => 'No' ),
		'#required' => FALSE,
	);
	$form['yoga_since'] = array(
		'#title' => t('How long have you practiced Yoga?'),
		'#type' => 'textfield',
		'#default_value' => '',
		'#required' => FALSE,
	);
	$form['yoga_style'] = array(
		'#title' => t('If your practice focusses on a primary style or school, which one? '),
		'#type' => 'textfield',
		'#default_value' => '',
		'#required' => FALSE,
	);
	$form['gender'] = array(
		'#title' => t('Gender'),
		'#type' => 'radios',
		'#options' => array( 'Female' => 'Female', 'Male' => 'Male' ),
		'#required' => FALSE,
	);
	$form['ski_or_snowboard'] = array(
		'#title' => t('Do you ski or snowboard?'),
		'#type' => 'radios',
		'#options' => array( 'Yes' => 'Yes', 'No' => 'No' ),
		'#required' => FALSE,
	);
	$form['education'] = array(
		'#title' => t('Education'),
		'#type' => 'radios',
		'#options' => array( 'High school'=>'High school', 'Enrolled in college'=>'Enrolled in college', 'College grad'=>'College grad', 'Graduate school' => 'Graduate school +' ),
		'#required' => FALSE,
	);
	$form['work_status'] = array(
		'#title' => t('Current work status'),
		'#type' => 'radios',
		'#options' => array( 'Work part time'=>'Work part time', 'Work full time'=>'Work full time', 'Not currently working'=>'Not currently working' ),
		'#required' => FALSE,
	);
	
	$form['computer_msword'] = array(
		'#prefix' => "<div class=\"form-item\"><label>Computer Skills - How familiar are you with the following:</label></div>",
		'#title' => t('MS Word'),
		'#type' => 'radios',
		'#options' => array( 'No clue'=>'No clue', 'Somewhat familiar'=>'Somewhat familiar', 'Expert'=>'Expert' ),
		'#required' => FALSE,
	);
	$form['computer_excel'] = array(
		'#title' => t('MS Excel'),
		'#type' => 'radios',
		'#options' => array( 'No clue'=>'No clue', 'Somewhat familiar'=>'Somewhat familiar', 'Expert'=>'Expert' ),
		'#required' => FALSE,
	);
	$form['computer_photoshop'] = array(
		'#title' => t('Photoshop'),
		'#type' => 'radios',
		'#options' => array( 'No clue'=>'No clue', 'Somewhat familiar'=>'Somewhat familiar', 'Expert'=>'Expert' ),
		'#required' => FALSE,
	);
	$form['computer_illustrator'] = array(
		'#title' => t('Illustrator'),
		'#type' => 'radios',
		'#options' => array( 'No clue'=>'No clue', 'Somewhat familiar'=>'Somewhat familiar', 'Expert'=>'Expert' ),
		'#required' => FALSE,
	);
	$form['computer_html'] = array(
		'#title' => t('HTML'),
		'#type' => 'radios',
		'#options' => array( 'No clue'=>'No clue', 'Somewhat familiar'=>'Somewhat familiar', 'Expert'=>'Expert' ),
		'#required' => FALSE,
	);
	$form['computer_socialnet'] = array(
		'#title' => t('Social Networking'),
		'#type' => 'radios',
		'#options' => array( 'No clue'=>'No clue', 'Somewhat familiar'=>'Somewhat familiar', 'Expert'=>'Expert' ),
		'#required' => FALSE,
	);
	$form['computer_web'] = array(
		'#title' => t('Web Navigation'),
		'#type' => 'radios',
		'#options' => array( 'No clue'=>'No clue', 'Somewhat familiar'=>'Somewhat familiar', 'Expert'=>'Expert' ),
		'#required' => FALSE,
	);
	
	$form['fitness'] = array(
		'#title' => t('How would you rate your ability to perform strenuous labor?'),
		'#type' => 'radios',
		'#options' => array( 'Desk jobs'=>'I\'m only suited for desk jobs.', 'Light physical'=>'I can do light physical work for a few hours.', 'Medium labor'=>'I\'m in solid shape. Can do some medium labor if required.', 'Bring it on'=>'I\'m strong and fit. Bring it on.' ),
		'#required' => FALSE,
	);

	$form['available_wednesday'] = array(
		'#prefix' => "<div class=\"form-item\"><label>What festival days and times are you available to work?</label></div>",
		'#title' => t('Wednesday, July 28th'),
		'#type' => 'checkboxes',
		'#options' => array( 'Morning' => 'Morning', 'Afternoon' => 'Afternoon', 'Night' => 'Night', 'Not available' => 'Not available' ),
		'#required' => TRUE,
	);

	$form['available_thursday'] = array(
		'#title' => t('Thursday'),
		'#type' => 'checkboxes',
		'#options' => array( 'Morning' => 'Morning', 'Afternoon' => 'Afternoon', 'Night' => 'Night', 'Not available' => 'Not available' ),
		'#required' => TRUE,
	);

	$form['available_friday'] = array(
		'#title' => t('Friday'),
		'#type' => 'checkboxes',
		'#options' => array( 'Morning' => 'Morning', 'Afternoon' => 'Afternoon', 'Night' => 'Night', 'Not available' => 'Not available' ),
		'#required' => TRUE,
	);

	$form['available_saturday'] = array(
		'#title' => t('Saturday'),
		'#type' => 'checkboxes',
		'#options' => array( 'Morning' => 'Morning', 'Afternoon' => 'Afternoon', 'Night' => 'Night', 'Not available' => 'Not available' ),
		'#required' => TRUE,
	);

	$form['available_sunday'] = array(
		'#title' => t('Sunday'),
		'#type' => 'checkboxes',
		'#options' => array( 'Morning' => 'Morning', 'Afternoon' => 'Afternoon', 'Night' => 'Night', 'Not available' => 'Not available' ),
		'#required' => TRUE,
	);

	$form['available_monday'] = array(
		'#title' => t('Monday'),
		'#type' => 'checkboxes',
		'#options' => array( 'Morning' => 'Morning', 'Afternoon' => 'Afternoon', 'Night' => 'Night', 'Not available' => 'Not available' ),
		'#required' => TRUE,
	);
	
	$form['yoga_day'] = array(
		'#title' => t('Which day would you like to have free for practicing yoga (if you practice)?'),
		'#type' => 'radios',
		'#options' => array( 'Thursday' => 'Thursday', 'Friday' => 'Friday', 'Saturday' => 'Saturday', 'Sunday' => 'Sunday' ),
		'#required' => FALSE,
	);
	
	$interest_options = array( 'none selected'=>'- select one -', 'Artist / yoga teacher relations'=>'Artist / yoga teacher relations', 'Audio / Video'=>'Audio / Video', 'Customer Service'=>'Customer Service', 'Food / Catering'=>'Food / Catering', 'Greening / Environmentalism'=>'Greening / Environmentalism', 'Merchandise Sales'=>'Merchandise Sales', 'Music Production'=>'Music Production', 'Vendor Relations'=>'Vendor Relations', 'Yoga Class Production'=>'Yoga Class Production' );
	
	$form['interest_1'] = array(
		'#title' => t('Please select your FIRST choice from the following areas of interest'),
		'#type' => 'select',
		'#options' => $interest_options,
		'#required' => FALSE,
	);
	$form['interest_2'] = array(
		'#title' => t('Please select your SECOND choice from the following areas of interest'),
		'#type' => 'select',
		'#options' => $interest_options,
		'#required' => FALSE,
	);
	$form['interest_3'] = array(
		'#title' => t('Please select your THIRD choice from the following areas of interest'),
		'#type' => 'select',
		'#options' => $interest_options,
		'#required' => FALSE,
	);
	$form['math'] = array(
		'#title' => t('Are you good at math'),
		'#type' => 'radios',
		'#options' => array( 'Whiz'=>'I\'m a whiz', 'Good'=>'Pretty good', 'No'=>'No' ),
		'#required' => FALSE,
	);
	$form['blog'] = array(
		'#title' => t('Do you regularly blog?'),
		'#type' => 'radios',
		'#options' => array( 'Yes' => 'Yes', 'No' => 'No' ),
		'#required' => FALSE,
	);	
	$form['blog_url'] = array(
		'#title' => t('If you answered yes, please provide a link to your blog'),
		'#type' => 'textfield',
		'#required' => FALSE,
	);
	$form['photos'] = array(
		'#title' => t('Do you regularly take photos or shoot/edit video?'),
		'#type' => 'radios',
		'#options' => array( 'Yes' => 'Yes', 'No' => 'No' ),
		'#required' => FALSE,
	);
	$form['photo_info'] = array(
		'#title' => t('If yes, do you have your own equipment you can bring to the festival? If so, what is it?'),
		'#type' => 'textarea',
		'#required' => FALSE,
	);
	$form['festival_exp'] = array(
		'#title' => t('Do you have festival experience?'),
		'#type' => 'radios',
		'#options' => array( 'Yes' => 'Yes', 'No' => 'No' ),
		'#required' => FALSE,
	);	
	$form['festival_exp_info'] = array(
		'#title' => t('If you answered yes, which festivals? Tell us a little about what you did at those festivals'),
		'#type' => 'textarea',
		'#required' => FALSE,
	);
	$form['job_desired'] = array(
		'#title' => t('Which job would you most like to do at Wanderlust. Why?'),
		'#type' => 'textarea',
		'#required' => FALSE,
	);
	$form['shift_lead_ok'] = array(
		'#title' => t('Would you be interested in being considered for a shift lead position?'),
		'#type' => 'radios',
		'#options' => array( 'Yes' => 'Yes', 'No' => 'No' ),
		'#required' => FALSE,
	);	
	$form['volunteer'] = array(
		'#title' => t('Do you volunteer?'),
		'#type' => 'radios',
		'#options' => array( 'Yes' => 'Yes', 'No' => 'No' ),
		'#required' => FALSE,
	);
	$form['volunteer_info'] = array(
		'#title' => t('If yes, what type of volunteer work do you do?'),
		'#type' => 'textarea',
		'#required' => FALSE,
	);
	$form['extra_info'] = array(
		'#title' => t('Anything else we should know when considering your application?'),
		'#type' => 'textarea',
		'#required' => FALSE,
	);
	$form['how_found_out'] = array(
		'#title' => t('How did you hear about volunteering for Wanderlust?'),
		'#type' => 'textfield',
		'#required' => FALSE,
	);

	$form['cc_num'] = array(
		'#prefix' => "<div class=\"heading1\">Billing Info</div>",
		'#title' => t('Credit Card Number'),
		'#type' => 'textfield',
		'#required' => TRUE,
	);
	$form['cc_expires'] = array(
		'#title' => t('Credit Card Expiration Date'),
		'#type' => 'textfield',
		'#description' => 'Ex: 12/12',
		'#required' => TRUE,
	);
	$form['cc_cvc'] = array(
		'#title' => t('Card Verification Code'),
		'#type' => 'textfield',
		'#required' => TRUE,
	);
	$form['cc_first_name'] = array(
		'#title' => t('First Name on Card'),
		'#type' => 'textfield',
		'#required' => TRUE,
	);
	$form['cc_last_name'] = array(
		'#title' => t('Last Name on Card'),
		'#type' => 'textfield',
		'#required' => TRUE,
	);
	$form['bill_street_address'] = array(
		'#title' => t('Billing Street Address'),
		'#type' => 'textfield',
		'#required' => TRUE,
	);
	$form['bill_city'] = array(
		'#title' => t('Billing City'),
		'#type' => 'textfield',
		'#required' => TRUE,
	);
	$form['bill_state'] = array(
		'#title' => t('Billing State'),
		'#type' => 'textfield',
		'#required' => TRUE,
	);
	$form['bill_zip'] = array(
		'#title' => t('Billing Zip'),
		'#type' => 'textfield',
		'#required' => TRUE,
	);
	
	// ============================ 
	
	$form['submit'] = array(
		'#type' => 'submit',
		'#value' => t('Submit'),
	);
	return $form;
	
}

/**
 * wl_volunteer_volform_validate function.
 * 
 */
function wl_volunteer_volform_validate($form, &$form_state){

	if(!preg_match("/^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}$/",$form_state['values']['email'])){
		form_set_error('email', t('Please provide a valid email address.'));
	}

}

function wl_volunteer_volform_submit($form, &$form_state){
	
	$email = $form_state['values']['email'];
		
	if (count(array_filter($form_state['values']['email_subscribe'])) > 0) {

		$cleaned_email = urlencode(strip_tags($form_state['values']['email_subscribe']));
		$data_pairs = array('Email Address='.$cleaned_email,
												'thx=http://www.velourmusic.com/email-list/thankyou.html',
												'err=http://www.velourmusic.com/email-list/error.html',
												'usub=http://www.velourmusic.com/email-list/unsubscribe.html',
												'MID=119246',
												'SubAction=sub_add_update',
												);
		$post_data = join('&', $data_pairs);
		
		// And submit it behind the scenes
		_send($post_data, 'http://cl.exct.net/subscribe.aspx?lid=15928006');
		
	}

	$volunteer_table = "wl_volunteer";
	$volunteer_data = new stdClass();
	$report = '';
	$report_internal = '';
	
	$ignore_form_fields = 'op,submit,form_build_id,form_id';
	$ignore_array = explode(',',$ignore_form_fields);
	
	foreach($form_state['values'] as $key=>$value){
		if(is_array($value)){
			$volunteer_data->$key = implode(',',array_filter($value));
		} else {
			$volunteer_data->$key = $value;
		}
		
		if(!in_array($key,$ignore_array)){
			if($key == 'cc_num'){
				$report.=$key.": (last 4) ".substr($volunteer_data->$key, -4)."\n---------------------------\n";
			} elseif($key == 'cc_cvc'){
				$report.=$key.": (hidden)\n---------------------------\n";
			} else {
				$report.=$key.": ".$volunteer_data->$key."\n---------------------------\n";
			}
		}
		if(!in_array($key,$ignore_array)){
			$report_internal.=$key.": ".$volunteer_data->$key."\n---------------------------\n";
		}
	}
		
//	error_log(print_r($volunteer_data,TRUE));
//	error_log('---------');
//	error_log(print_r($form_state,TRUE));

	
	drupal_write_record($volunteer_table, $volunteer_data);
	
	
	// send form contents to admin
	$email_intro = "Thanks very much for applying to become a volunteer at Wanderlust 2010.  We'll review your application shortly and will be in touch if we have any additional questions.  Final decisions will be announced on a rolling basis via email starting June 1, 2010.  If you have any questions, please email us at volunteer@wanderlustfestival.com.\n\nHope to see you on the cable car.\n\n- Kat Murray, Volunteer Coordinator\n\nBelow is a copy of the information you provided:\n\n---------------------------\n";
	$email_message = $email_intro.$report;
	$email_message2 = $email_intro.$report_internal;
	$subject = 'Wanderlust Volunteer Form Received';
	
	//error_log($email_message);
	$message = array(
	  'id' => 'wl_volunteer_form',
	  'to' => $email,
	  'subject' => $subject,
	  'body' => $email_message,
	  'headers' => array('From' => 'volunteer@wanderlustfestival.com'),
	);
	drupal_mail_send($message);
	
	$message = array(
	  'id' => 'wl_volunteer_form',
	  'to' => 'volunteer@wanderlustfestival.com', //, support@malkine.com
	  'subject' => $subject,
	  'body' => $email_message2,
	  'headers' => array('From' => 'volunteer@wanderlustfestival.com'),
	);
	drupal_mail_send($message);

	
	drupal_set_message(t('Volunteer form successfully submitted.'));
	

	if(isset($_GET['friends']) && $_GET['friends']==1){
		drupal_goto('volunteer-form-complete');
	} else {
		drupal_goto('https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=3KHFN3SQG8E66&notify_url='.urlencode('http://'.$_SERVER['HTTP_HOST'].'/volunteer-form-capture-payment'));
	}

	
}

function _send($data, $url) {

	if($fp = tmpfile()){
		$ch = curl_init($url);
		curl_setopt($ch, CURLOPT_POST,1);
		curl_setopt($ch, CURLOPT_POSTFIELDS,$data);
		curl_setopt($ch, CURLOPT_STDERR, $fp);
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
		$output = curl_exec($ch);
	}

	curl_close($ch);

// Uncomment these to see debug information
//  drupal_set_message($url);
//  drupal_set_message($data);
//  drupal_set_message($output);
 
}

