<?php

$GLOBALS['_artist_node_twitter_field'] = 'field_twitter_username';
require_once 'wl_helper.blocks.inc';
require_once 'wl_helper.base_domain.inc';

function wl_helper_boot() {
  // only read the cookie and redirect if we're not on one of the subdomains already, we're not on the splash page, and the user is not the superuser
  global $user;
  $url = explode('.', str_replace('http://', '', $_SERVER['HTTP_HOST']));
  $subdomain = strtolower(trim($url[0]));
  if ($subdomain == 'wanderfest' && ($_GET['q'] != 'front-splash') && $user->uid != 1) {
  /*  $sid = sites_get_most_recent_visited_site_sid();

    if (!empty($sid)) {
      $prev_site = _sites_get_site($sid);



      drupal_goto('http://' . $prev_site->purl_prefix . '.' . wl_get_base_domain() . '');
    }*/
  }
  else {
    $arr = array(
      'squaw' => 1,
      'stratton' => 3,
      'cosmo' => 7,
      'standard' => 8,
      'colorado' => 21,
      'whistler' => 22,
      'oahu' => 23,
      'chile' => 24,
    );

/*    @sites_set_current_site(_sites_get_site($arr[$subdomain]));
    sites_set_current_site_cookie();*/
  }
}

function wl_helper_init() {

  //drupal_add_css(drupal_get_path('module','wl_helper') . '/wl_helper.css');

  //drupal_set_header('Access-Control-Allow-Origin: *');

 // $mystring = $_SERVER['HTTP_REFERER'];
//print '<pre>' . print_r($_SERVER['HTTP_REFERER'], 1) . '</pre>';
//  $find   = '.wonderlustfest.com';
//  $pos = strpos($mystring, $find);
 // print '<pre>pos' . print_r($pos, 1) . '</pre>';
 // $url = explode('.', str_replace('http://', '', $_SERVER['HTTP_HOST']));
 // $subdomain = strtolower(trim($url[0]));
  //if ($subdomain == 'wonderlustfest' && !$_GET['m']) {
   // drupal_add_js(drupal_get_path('module','wl_helper') . '/wl_helper_map.js');

 // }


  if (isset($_GET['set_purl_base_domain']) && $_GET['set_purl_base_domain'] == '1') {
    variable_set('purl_base_domain', 'http://' . wl_get_base_domain());
  }

  global $user;
  $site = sites_get_current_site();
  // If current site is disabled, redirect to default site.
  global $language;
  $languages = language_list();
  if($site->purl_prefix != 'tremblant') {
    $new_lang_code = 'en';
    if (isset($languages[$new_lang_code])) {
      $language = $languages[$new_lang_code];
    }
  }
  elseif($site->purl_prefix == 'tremblant' &&  isset($_COOKIE['wanlang'])) {
    $new_lang_code = $_COOKIE['wanlang'];
    if (isset($languages[$new_lang_code])) {
      $language = $languages[$new_lang_code];
    }
  }
  
  /*else {
     $new_lang_code = 'en';
     $language = $languages[$new_lang_code];
  }*/



//  drupal_set_message('<pre>' . print_r($language->language, 1) . '</pre>');
  //purl_prefix
  //[extra_fields][field_event_hide][0] [value] => enabled
  if (!empty($site) && $user->uid != 1 && $user->uid != 4482) {
    if(isset($_COOKIE['mysite'])  &&  $_COOKIE['mysite'] == $site->purl_prefix && $site->extra_fields->field_event_hide[0]['value'] == 'disabled') {
        //drupal_set_message('<pre>' . print_r($_COOKIE['mysite']. 'aa', 1) . '</pre>');
	drupal_goto('http://' . wl_get_base_domain(), array('m' => 1));
    }
    
    
	$disabled = array();
    $disabled = wl_helper_disabled_sites();


    if (in_array($site->sid, $disabled)) {
      drupal_goto('http://' . wl_get_base_domain(), array('m' => 1));
    }
  }


//drupal_set_message('<pre>' . print_r(wl_get_base_domain(), 1) . '</pre>');
  // only read the cookie and redirect if we're not on one of the subdomains already, we're not on the splash page, and the user is not the superuser
/*  if ($_GET['q'] != 'live-events-list.json') {
    global $user;

    if ((!($site)) && ($_GET['q'] != 'front-splash') && $user->uid != 1) {
      $sid = sites_get_most_recent_visited_site_sid();

      if (!empty($sid)) {
        $prev_site = _sites_get_site($sid);
        drupal_goto('http://' . $prev_site->purl_prefix . '.' . wl_get_base_domain());
      //  drupal_goto('http://cosmopolitan.' . wl_get_base_domain() . '/home');

      }
      else {
     //  drupal_goto('http://oahu.' . wl_get_base_domain() . '/home');
      }
    }
  }*/
  /*$msg = variable_get('wl_messages', 'NO MESSAGES');
  if ($msg != 'NO MESSAGES') {
    $msg = unserialize($msg);
  }
  //dsm($msg, 'MESSAGES!');*/

}




function wl_helper_sites_node_access_alter(&$permitted, $node) {
  global $user;
  if ($user->uid > 1 && $user->uid != 4482) {
    $site = sites_get_current_site();
    if ($site) {
      if ($site->extra_fields->field_event_hide[0]['value'] == 'disabled') {
        $permitted = FALSE;
      }
    }
  }

  if (stristr($_SERVER['HTTP_USER_AGENT'], 'facebookexternalhit')) { // allow facebook bot to see all nodes so that comments can be shared across all sites
    $permitted = TRUE;
  }
}


/* DISABLED BY ARTHUR 11-14-12
function wl_helper_cron() {
  // Update cached Twitter statuses for all stored Twitter usernames
  $field = content_fields($GLOBALS['_artist_node_twitter_field']);
  $db_info = content_database_info($field);
  $result = db_query("SELECT DISTINCT(cck_tw." . $db_info['columns']['value']['column'] . ") AS username FROM {". $db_info['table'] ."} cck_tw");
  if (!function_exists('twitter_fetch_timeline')) {
    module_load_include('inc', 'twitter');
  }

  $names = variable_get('wl_remaining_twitter_accts', NULL);
  if (!$names) {
    $names = array();
    while($row = db_fetch_object($result)) {
      $names[] = $row->username;
    }
  }
  else {
    if (!is_array($names)) {
      $names = unserialize($names);
    }
    //dsm($names, 'remaining');
  }

  $i = 0;
  while ($i < 10 && count($names) > 0) {
    $name = array_shift($names);
    //dsm(twitter_fetch_timeline($name), 'twitter_fetch_timeline ' . $name);
    $i++;
    //dsm('updating twitter status for ' . $name);
  }
  variable_set('wl_remaining_twitter_accts', serialize($names));
}

*/



function wl_helper_nodeapi(&$node, $op, $teaser, $page) {
  // expose twitter username for views_arg_context on artist nodes
  if($node->type == 'artists') {
    context_set('wl_current_node', 'twitter_username', $node->{$GLOBALS['_artist_node_twitter_field']}[0]['value']);
  }
}




function wl_msg($title, $message = NULL) {
  static $page_load_id = NULL;
  if (!$page_load_id) {
    $page_load_id = date('G:i:s:u');
  }

  $msg = variable_get('wl_messages', '');
  $msg = unserialize($msg);
  if (!is_array($msg)) {
    $msg = array();
  }
  if (!isset($msg[$page_load_id])) {
    $msg[$page_load_id] = array();
  }
  $msg[$page_load_id][] = array($title => ($message ? $message : $title));
  variable_set('wl_messages', serialize($msg));
}

function wl_helper_menu() {
  $items['home'] = array(
    'title' => 'Wanderlust Festival: Home',
    'description' => '',
    'page callback' => 'wl_page_home',
    'access callback' => TRUE,
  );

  $items['front-splash'] = array(
    'title' => 'Wanderlust Festival: All events splash page',
    'description' => '',
    'page callback' => 'wl_page_splash',
    'access callback' => TRUE,
  );

  $items['live-events-list.json'] = array(
    'title' => '',
    'description' => '',
    'page callback' => 'wl_feed_live_events_list',
    'access callback' => TRUE,
  );

  $items['getimages'] = array(
    'page callback' => 'wl_helper_getimages_ajax',
    'type' => MENU_CALLBACK,
    'access arguments' => array('access content'),
  );

  $items['getvideo'] = array(
    'page callback' => 'wl_helper_getvideo_ajax',
    'type' => MENU_CALLBACK,
    'access arguments' => array('access content'),
  );
  return $items;
}

function wl_helper_getimages_ajax($nid) {
  if($nid) {
   $data = db_query("SELECT photos_images.filepath AS filepath, node_data_field_photos_images.field_photos_images_data AS tit
				  FROM {node} node
				  LEFT JOIN {content_field_photos_images} node_data_field_photos_images ON node.vid = node_data_field_photos_images.vid
				  LEFT JOIN {files} photos_images ON node_data_field_photos_images.field_photos_images_fid = photos_images.fid
				  WHERE node.nid = %d", $nid);
    $output = '';
    $title = '';
    $i = 0;
	while($res = db_fetch_object($data)) {
	  $i++;
	  $title = @unserialize($res->tit);
	//  print '<pre>' . print_r($title, 1) . '</pre>';
	  if($i == 1) {
	    	 $output .= '<p><a class="hid fir" data-fancybox-group="thumb" title ="' . $title['description'] . '" href="/' . $res->filepath . '">' . theme('imagecache', 'node_teaser_image', $res->filepath) . '</a></p>';
	  }
	//  $output .=  '<p><a class="hid" data-fancybox-group="thumb"  href="/' . $res->files_node_data_field_photos_images_filepath . '">' . theme('imagecache', 'node_teaser_image', $res->files_node_data_field_photos_images_filepath) . '</a></p>';
	  else {
	      $output .= '<p><a class="hid" data-fancybox-group="thumb" title ="' . $title['description'] . '" href="/' . $res->filepath . '">' . theme('imagecache', 'node_teaser_image', $res->filepath) . '</a></p>';
	    //  $output .= '<p><a class="hid" data-fancybox-group="thumb"  href="/' . $res->filepath . '"><img src="/' . $res->filepath . '" alt="" /></a></p>';
	  }
	}

  }
  else {
    $output = t('No images');
  }

print $output;
  exit();
}

function wl_helper_getvideo_ajax($nid) {
  if($nid) {
    $output = '';
    $node = node_load($nid);
    $output .= '<div id="ajaxvid" style="display:none;">' . node_view($node) . '</div>';
  }
  else {
    $output = t('No video');
  }

print $output;
  exit();
}

function wl_feed_live_events_list() {
  $live = array();
  foreach (_sites_get_sites() as $site) {
    if ($site->extra_fields->field_event_hide[0]['value'] != 'disabled') {
      $live[] = $site;
    }
  }
  drupal_set_header('Content-Type: text/javascript; charset=utf-8');
  echo json_encode($live);
  exit;
}

function wl_page_home() {
  return '';
}

function wl_page_splash() {
  if (function_exists('front_page')) {
    front_page();
  }
  else {
    drupal_goto('home');
  }
}





function wl_helper_block($op = 'list', $delta = 0, $edit = array())  {
  switch ($op) {
    case 'list':
      $blocks = array();
      $blocks['home_page_photos_tab'] = array(
        'info' => t('WL: Home page "Photos & videos" tab'),
      );
      $blocks['home_page_connect_tab'] = array(
        'info' => t('WL: Home page "Connect" tab'),
      );
      $blocks['lineup_copy'] = array(
        'info' => t('WL: Lineup copy'),
      );
      /*$blocks['smart_menu'] = array(
        'info' => t('WL: Smart 2nd level menu block'),
      );*/
      return $blocks;
      break;


    case 'configure':
      $function = 'wl_helper_blocks_'. $delta .'_configure';
      if (function_exists($function)) {
        return $function();
      }
      break;

    case 'save':
      $function = 'wl_helper_blocks_'. $delta .'_save';
      if (function_exists($function)) {
        return $function($edit);
      }
      break;


    case 'view':
      $function = 'wl_helper_blocks_'. $delta;
      $block = function_exists($function) ? $function() : array();
      return $block;
      break;
  }
}

// set front page title
function wl_helper_page_title_alter(&$title) {
  $site = sites_get_current_site();

  if ($_GET['q'] == 'home') {
    if ($site->extra_fields) {
      $date_start = strtotime($site->extra_fields->field_event_date[0]['value']);
      $event_date = date('F j', $date_start);
      if ($site->extra_fields->field_event_date[0]['value2'] != $site->extra_fields->field_event_date[0]['value']) {
        $date_end = strtotime($site->extra_fields->field_event_date[0]['value2']);
        $event_date .= '-' . date('j, Y', $date_end);
      }
      $fields = array('Wanderlust Festival',
                      $event_date,
                      $site->extra_fields->field_event_city[0]['value'] . ', ' . $site->extra_fields->field_event_state[0]['value'],
                      'Yoga, Music, Nature');

      $title = implode(' ~ ', $fields);
    }
  }
  else {
    $title = $site->title . ' | ' . $title;
  }
}



function wl_helper_get_fbook_app_id() {
  $ids = array(
    'wanderlustfestival.com' => '321576251186267',
    'wanderfest.com' => '170029253037850',
    'rusticovertonesmusic.com' => '202279093186680',
  );

  return $ids[wl_get_base_domain()];
}


function wl_helper_views_pre_render(&$view) {

  if ($view->name == 'artist_landing') {
    if (count($view->result) <= 1) {
      $view->result = array();
    }
  }
  if ($view->name == 'all_blog_posts') {
    //$view->display['page_1']->display_options['path']='/';
    //$view->display['page_1']->handler->options['path'] = '/';
    //file_put_contents('v.txt', print_r($view->display['page_1'],true));
  }
}


/**
 * Implementation of hook_form_FORM_ID_alter()
 */
function wl_helper_form_views_exposed_form_alter(&$form, &$form_state) {
  $sites = _sites_get_sites();
  foreach ($sites as $site) {
    $sids[$site->tid] = $site->sid;
  }

  $field_name = 'field_event_hide';
  $field = content_fields($field_name);
  $db_info = content_database_info($field);
  $options = $form['tid_1']['#options'];
  unset($form['tid_1']['#options'][33]);
  unset($options['All']);
  unset($options[33]);


  foreach ($options as $tid => $value) {
    $nid = sites_extra_fields_get_associated_nid($sids[$tid]);
    $vid = db_result(db_query("SELECT n.vid FROM {node} n WHERE n.nid = %d", $nid));
    $status = db_result(db_query("SELECT %s FROM {%s} WHERE vid=%d", $db_info['columns']['value']['column'], $db_info['table'], $vid));
    if ($status == 'disabled') unset($form['tid_1']['#options'][$tid]);
  }
}


/**
 * Get array of disabled sites
 */
function wl_helper_disabled_sites() {
  $sites = _sites_get_sites();
  global $user;
 /* if($user->uid == 1) {
     drupal_set_message('<pre>' . print_r($sites , 1) . '<pre>');
  }*/


  foreach ($sites as $site) {
 //   if ($site->sid == 23 && $user->uid ==0)  continue;
    $sids[] = $site->sid;
  }
  $field_name = 'field_event_hide';
  $field = content_fields($field_name);
  $db_info = content_database_info($field);

  $disabled = array();
  if(!empty($sids)):
  foreach ($sids as $sid) {
    $nid = sites_extra_fields_get_associated_nid($sid);
    $vid = db_result(db_query("SELECT n.vid FROM {node} n WHERE n.nid = %d", $nid));
    $status = db_result(db_query("SELECT %s FROM {%s} WHERE vid=%d", $db_info['columns']['value']['column'], $db_info['table'], $vid));
    if ($status == 'disabled') $disabled[] = $sid;
  }
  endif;

  return $disabled;
}


function wlw_helper_preprocess_views_view(&$vars) {
  global $base_path;

  $view = $vars['view'];
  $empty = !(bool) count($view->result);
  $settings = variable_get('viewsdisplaytabs_settings', array());
  $show = ( $empty ? $empty && $settings['view_show_empty'][$view->name] == 1 : true );

  if ($settings['view_enabled'][$view->name] == 1 && $show) {
    $selected_displays = $settings['view_displays'][$view->name];

    // Collect displays and build grouping array
    // If no displays are selected, include all displays
    foreach ($view->display as $display_name => $display_data) {
      if (!$selected_displays || !count($selected_displays) || in_array($display_name, $selected_displays)) {

        // Allow grouping of tabs with grouping separator in titles/names: group[sep]title
        // If the separator is at position 0 or does not exist it all, do not group
        $sep = $settings['view_group_separator'][$view->name];
        if ($sep && strpos($display_data->display_title, $sep)) {

          list($group, $title) = explode($sep, $display_data->display_title);
        }
        else {
          $title = $display_data->display_title;
          $group = 0;
        }

        // Set current tab as active based on URL query params
        $current_view_display = _viewsdisplaytabs_get_current_views_display_from_url();
        if ($current_view_display && $view->name == $current_view_display->view_name) {
          $active = ( $display_name == $current_view_display->display_name );
        }
        else {
          $active = ( $display_name == $settings['view_displays_default'][$view->name] );
        }

        // Build a grouping array for later
        // @TODO: Pass the path of the display as well, provided it has been set
        // (true for page displays).
        $displays[$group][] = theme('viewsdisplaytabs_tab', $title, $_GET['q'], $view->name, $display_name, $active);
      }
    }

    // Build header, exclude displays that are attachments (or we'll end up
    // with two sets of tabs)

     unset($displays[0][5]);

    if ($view->display_handler->definition['handler'] != 'views_plugin_display_attachment') {
      $header .= theme('viewsdisplaytabs_tab_groups', $displays, 'viewsdisplaytabs-tab-group');
    }

    // Assign header
    $vars['header'] .= $header;

    // Add JS
    $js = drupal_add_js();
    $js['setting']['viewsdisplaytabs']['views'][$view->name] = $view->name;
    $js['setting']['viewsdisplaytabs']['default_display'][$view->name] = $settings['view_displays_default'][$view->name];
    $js['setting']['viewsdisplaytabs']['view_throbber'][$view->name] = $settings['view_throbber'][$view->name];
    drupal_add_js($js['setting'], 'setting');
    drupal_add_js(drupal_get_path('module', 'viewsdisplaytabs') .'/viewsdisplaytabs.js');
    drupal_add_js('misc/jquery.form.js');
  }
}

function wl_helper_menu_alter(&$items) {
  /*
  file_put_contents('m.txt', print_r($items,true));
*/
/* //This works but we don't need it now
  $ob = $items['blog'];
  unset ($items['blog']);
  $items['_blog'] = $ob;

  $ob = $items['blog/%user_uid_optional'];
  unset ($items['blog/%user_uid_optional']);
  $items['_blog/%user_uid_optional'] = $ob;

  $ob = $items['blog/%user/feed'];
  unset ($items['blog/%user/feed']);
  $items['_blog/%user/feed'] = $ob;

  $ob = $items['blog/feed'];
  unset ($items['blog/feed']);
  $items['_blog/feed'] = $ob;
*/
}
/*
function wl_helper_views_pre_render(&$view) {
  file_put_contents('v.txt', print_r($view,true), FILE_APPEND);
}
*/
