<?php
// $Id$
/**
 * @file wander_fb.module
 * Implements facebook connect functionality for Wanderlust site.
 *
 * Requires the 'Drupal for Streams' module as well as 'Comments'.
 */

/**
 * Implementation of hook_form_alter.
 *
 * Adds a checkbox to comment forms.  This checkbox lets
 * facebook users know that content may be published to their Wall,
 * and gives them a chance to prevent that.
 */
function wander_fb_form_alter(&$form, $form_state, $form_id) {

  if (isset($GLOBALS['fb']) && fb_facebook_user()) {

    
    if ($form['form_id']['#value'] == 'comment_form') {
      // Add checkbox to control feed publish.
      $form['dff_custom']['stream_publish'] = array(
        '#type' => 'checkbox',
        '#title' => '<img src="/sites/all/themes/wanderlust/images/grafix/fb_small.gif" /> Share on Facebook',
        '#default_value' => TRUE,
      );
    }

	
  } else if (isset($GLOBALS['fb']) && fb_facebook_user() == NULL) {

    if ($form['form_id']['#value'] == 'comment_form') {
      // Add extra login option.
      $form['dff_custom']['stream_publish'] = array(
        '#prefix' => '<div style="margin-bottom:10px;">',
        '#value' => '<fb:login-button v="2"><fb:intl>Connect with Facebook</fb:intl></fb:login-button>', // <a href="/user/">Login</a> or 
        '#suffix' => '</div>',
      );
    }
  } 

}



/**
 * Implementation of hook_comment().
 *
 * Publish to facebook Walls when users submit comments.
 */
function wander_fb_comment(&$a1, $op) {
  if ($op == 'insert' || $op == 'update') {
    if ($a1['stream_publish']) {
      //dpm($a1, "dff_custom_comment, publishing to stream");
      $node = node_load($a1['nid']);
     
      // http://wiki.developers.facebook.com/index.php/Attachment_(Streams)
      $attachment = array(
        'name' => $a1['subject'],
        'href' => url('node/' . $a1['nid'], array('absolute' => TRUE, 'fragment' => 'comment-' . $a1['cid'])),
        'description' => $a1['comment'],
        'properties' => array(t('In reply to') => array('text' => $node->title, 'href' => url("node/" . $node->nid, array('absolute' => TRUE)))),
      );

      $user_message = t('Check out my latest comment on !site',
                        array('!site' => variable_get('site_name', t('Wanderlust Festival'))));
      $actions = array();
      $actions[] = array('text' => t('Read More'),
                         'href' => url('node/'.$a1['nid'], array('absolute' => TRUE)),
      );
      fb_stream_publish_dialog(array('user_message' => $user_message,
                                     'attachment' => $attachment,
                                     'action_links' => $actions,
                               ));
    }
  }

}


