<?php

function wanderlust_custom_videos_init()
{
    drupal_add_js(drupal_get_path("module", "wanderlust_custom_videos") . '/wanderlust_custom_videos.js');
}
function wanderlust_custom_videos_menu() {
  $items = array();
  $items['wanderlust-videos'] = array(
    'page callback' => 'wanderlust_custom_videos_display',
	'page arguments' => array(arg(1)),
    'type' => MENU_CALLBACK,
    'access arguments' => array('access content')
   );
  
  
  return $items;

}
function wanderlust_custom_videos_block($op = 'list', $delta = 0, $edit = array())
{

}

function wanderlust_custom_videos_display($nid = '') {
  $out = views_embed_view("videos", "page_3", arg(1));
  $output = explode("watch?v=", $out);
  $output2 = explode("</span>", $output[1]);
  
  $data = '<script type="text/javascript" src="/sites/all/libraries/swfobject/swfobject.js?"></script>    
  <div id="ytapiplayer">
    You need Flash player 8+ and JavaScript enabled to view this video'.$output[1].'
  </div>

  <script type="text/javascript">

    var params = { allowScriptAccess: "always" };
    var atts = { id: "myytplayer" };
    swfobject.embedSWF("http://www.youtube.com/v/'.$output[1].'?enablejsapi=1&playerapiid=ytplayer&version=3",
                       "ytapiplayer", "425", "356", "8", null, null, params, atts);

  </script>';
    //Return JS if that's what was called for
    if (!empty($_POST['js']))
    {
        drupal_json(array(
            'video' => $output2[0]
        ));
        exit();
    } else
    {
        return $out;
    }
	
}