<?php

function dd_custom_block($op = 'list', $delta = 0, $edit = array()) {
  $block = array();
  $blocks = array();
  switch ($op) {
    case 'list':
        $blocks[0] = array(
          'info' => 'Megamenu Dropdown',
		  'cache' => BLOCK_NO_CACHE,
		  'title' => 'Megamenu Dropdown'
        );
        return $blocks;
      break;        
    
    case 'view':
        if ($delta == 0) {
			$block['content'] = sitesdropdown_create_menu();
		}
        return $block;
      break;      
  }
}